name: "Build"
on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
    - cron: "0 21 * * *"
jobs:
  build:
    name: Build ${{ matrix.rules }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rules: [domains, ips]
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
      - name: Checkout v2fly/domain-list-community
        if: matrix.rules == 'domains'
        uses: actions/checkout@v6
        with:
          repository: v2fly/domain-list-community
          path: domain-list-community
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v14
        with:
          name: blip
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build domain rules
        if: matrix.rules == 'domains'
        run: |
          mkdir -p release
          nix run .#gen-domains -- domain-list-community release
      - name: Build country IP rules
        if: matrix.rules == 'ips'
        env:
          MAXMIND_ACCOUNT_ID: ${{ secrets.MAXMIND_ACCOUNT_ID }}
          MAXMIND_LICENSE_KEY: ${{ secrets.MAXMIND_LICENSE_KEY }}
        run: |
          nix run .#gen-ips -- release
      - uses: actions/upload-artifact@v4
        with:
          name: rules-${{ matrix.rules }}
          path: release/
          if-no-files-found: error
  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/download-artifact@v5
        with:
          pattern: rules-*
          merge-multiple: true
          path: release/
      - name: Release
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: release
          folder: release
          single-commit: true
